import { Link } from 'react-router-dom';
import Icons from '../components/Icons';

function PrivacyPage() {
  return (
    <div className="container fade-in" style={{ paddingTop: '2rem', maxWidth: '800px', paddingBottom: '4rem' }}>
      <Link to="/" className="back-link" style={{ marginBottom: '2rem', display: 'inline-flex' }}>
        <Icons.ArrowLeft /> Back to Home
      </Link>
      <h1 style={{ fontSize: '3rem', marginBottom: '1.5rem' }}>Privacy Policy</h1>
      
      <div className="card-white" style={{ padding: '2rem', borderRadius: 'var(--radius-lg)', fontSize: '1.1rem', lineHeight: '1.6' }}>
        <p style={{ marginBottom: '2rem', fontSize: '1.4rem', fontWeight: '500' }}>
          At OS Tracker, we respect your privacy. This application is designed to be as stateless and privacy-respecting as technically possible. We firmly believe that your data belongs exclusively to you.
        </p>
        
        <h3 style={{ marginTop: '3rem', marginBottom: '1rem', fontSize: '2rem' }}>Data Collection & Usage</h3>
        <p style={{ marginBottom: '2rem' }}>
          OS Tracker operates on a strict zero-collection policy. We do <strong>not</strong> require you to create an account, log in, or provide any personally identifiable information (PII). We do not maintain a remote database of users, nor do we track, collect, aggregate, or sell your search history to advertising networks or third parties. All searches made through the platform interact directly with public APIs to retrieve publicly available developer statistics.
        </p>

        <h3 style={{ marginTop: '3rem', marginBottom: '1rem', fontSize: '2rem' }}>Third-Party APIs</h3>
        <p style={{ marginBottom: '2rem' }}>
          To function and provide real-time statistics, OS Tracker makes outbound requests to the official GitHub REST API. By using this tool to search for a developer, your IP address and standard browser headers may be exposed to GitHub as part of the standard HTTP request process. We recommend reviewing GitHub's own Privacy Statement for detailed information on how they handle incoming API requests.
        </p>

        <h3 style={{ marginTop: '3rem', marginBottom: '1rem', fontSize: '2rem' }}>Local Storage & Cookies</h3>
        <p style={{ marginBottom: '2rem' }}>
          We do not use tracking cookies, analytics scripts, or tracking pixels. However, to vastly improve your user experience, OS Tracker utilizes your browser's native <strong>Local Storage</strong> API. Your "Recent Searches", "Bookmarks", and "Theme Preferences" are saved securely and entirely locally within your own browser environment. This data never leaves your physical device and can be permanently deleted at any time by clearing your browser data or utilizing the built-in clear functions found in the app's sidebar menu.
        </p>

        <h3 style={{ marginTop: '3rem', marginBottom: '1rem', fontSize: '2rem' }}>User Rights</h3>
        <p style={{ marginBottom: '2rem' }}>
          Because we do not store your data on our servers, you inherently have full control over your "Right to be Forgotten". By clearing your browser cache and local storage, you erase all traces of your interaction with the OS Tracker application. There is no account deletion process necessary.
        </p>

        <h3 style={{ marginTop: '3rem', marginBottom: '1rem', fontSize: '2rem' }}>Security Measures</h3>
        <p style={{ marginBottom: '2rem' }}>
          Because OS Tracker does not store user data remotely, there is virtually zero risk of data breaches involving your personal information from our end. You are fully in control of the data generated by your use of the application. We force HTTPS to ensure that all data transmitted between your browser and the API remains encrypted in transit.
        </p>

        <h3 style={{ marginTop: '3rem', marginBottom: '1rem', fontSize: '2rem' }}>Changes to this Policy</h3>
        <p style={{ marginBottom: '2rem' }}>
          We reserve the right to update or modify this Privacy Policy at any time. If changes are made to how we handle local data or API integrations, this document will be updated accordingly. Continued use of OS Tracker after any changes indicates your acceptance of the new policy.
        </p>

        <h3 style={{ marginTop: '3rem', marginBottom: '1rem', fontSize: '2rem' }}>Contact Information</h3>
        <p style={{ marginBottom: '2rem' }}>
          If you have any questions, concerns, or feedback regarding this Privacy Policy or the open-source nature of the application, please feel free to open an issue on the project's official GitHub repository linked in the footer.
        </p>
      </div>
    </div>
  );
}

export default PrivacyPage;

// Ide sync commit
